version: '3'

services:
  nginx:
    build: 
      context: nginx
    container_name: nginx
    networks:
      - nodenet
    tty: true
    ports:
      - "8080:80"

  node:
    build: 
      context: node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh npm install node index.js
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
